export const DASHBOARD_LOADING = 'DASHBOARD_LOADING';

export const DASHBOARD_GET_SALOON = 'DASHBOARD_GET_SALOON';

export const DASHBOARD_ADD_SALON = 'DASHBOARD_ADD_SALON';

export const DASHBOARD_UPDATE_SALON = 'DASHBOARD_ADD_SALON';

export const DASHBOARD_UPDATE_SALON_LOGO = 'DASHBOARD_ADD_SALON';

export const DASHBOARD_ERROR = 'DASHBOARD_ERROR';

export const DASHBOARD_GET_SALOON_LIST = 'DASHBOARD_GET_SALOON_LIST';

