export const COUPANS_LOADING = 'COUPANS_LOADING'

export const COUPANS_GET_COUPANS = 'COUPANS_GET_COUPANS'

export const COUPANS_ADD_COUPANS = 'COUPANS_ADD_COUPANS'

export const COUPANS_GET_COUPANS_BY_ID = 'COUPANS_GET_COUPANS_BY_ID'

export const COUPANS_EDIT_COUPANS = 'COUPANS_EDIT_COUPANS'

export const COUPANS_RESET_COUPANS_BY_ID = 'COUPANS_RESET_COUPANS_BY_ID'

export const COUPANS_DELETE_COUPANS = 'COUPANS_DELETE_COUPANS'

export const COUPANS_ERROR = 'COUPANS_ERROR'

export const GET_SALON_BY_ID = 'GET_SALON_BY_ID'

export const RESET_SALON_BY_ID = 'RESET_SALON_BY_ID'
