export const CATEGORY_LOADING = 'CATEGORY_LOADING'

export const CATEGORY_GET_CATEGORY = 'CATEGORY_GET_CATEGORY'

export const CATEGORY_ADD_CATEGORY = 'CATEGORY_ADD_CATEGORY'

export const CATEGORY_EDIT_CATEGORY = 'CATEGORY_EDIT_CATEGORY'

export const CATEGORY_GET_CATEGORY_BY_ID = 'CATEGORY_GET_CATEGORY_BY_ID'

export const CATEGORY_ERROR = 'CATEGORY_ERROR'