export const AUTH_LOADING = 'AUTH_LOADING'

export const AUTH_SIGNUP = 'AUTH_SIGNUP'

export const AUTH_SIGNIN = 'AUTH_SIGNIN'

export const AUTH_ADMIN_SIGNIN = 'AUTH_ADMIN_SIGNIN'

export const AUTH_RESEND_OTP = 'AUTH_RESEND_OTP'

export const AUTH_RESET_PASSWORD = 'AUTH_RESET_PASSWORD'

export const AUTH_PROFILE_PIC = 'AUTH_PROFILE_PIC'

export const AUTH_USER_NAME = 'AUTH_USER_NAME'

export const AUTH_UPDATE_EMAIL = 'AUTH_UPDATE_EMAIL'

export const AUTH_UPDATE_PHONE = 'AUTH_UPDATE_PHONE'

export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD'

export const AUTH_CLOSE_MODAL = 'AUTH_CLOSE_MODAL'

export const AUTH_ERROR = 'AUTH_ERROR'