export const APPOINTMENT_LOADING = 'APPOINTMENT_LOADING'

export const APPOINTMENT_GET_APPOINTMENT = 'APPOINTMENT_GET_APPOINTMENT'

export const APPOINTMENT_ADD_APPOINTMENT = 'APPOINTMENT_ADD_APPOINTMENT'

export const APPOINTMENT_GET_APPOINTMENT_BY_ID = 'APPOINTMENT_GET_APPOINTMENT_BY_ID'

export const APPOINTMENT_EDIT_APPOINTMENT = 'APPOINTMENT_EDIT_APPOINTMENT'

export const APPOINTMENT_DELETE_APPOINTMENT = 'APPOINTMENT_DELETE_APPOINTMENT'

export const APPOINTMENT_ERROR = 'APPOINTMENT_ERROR'