export const EMPL_LOADING = 'EMPL_LOADING'

export const EMPL_GET_EMPLOYEE = 'EMPL_GET_EMPLOYEE'

export const EMPL_ADD_EMPLOYEE = 'EMPL_ADD_EMPLOYEE'

export const EMPL_GET_EMPLOYEE_BY_ID = 'EMPL_GET_EMPLOYEE_BY_ID'

export const EMPL_EDIT_EMPLOYEE = 'EMPL_EDIT_EMPLOYEE'

export const EMPL_DELETE_EMPLOYEE = 'EMPL_DELETE_EMPLOYEE'

export const EMPL_RESET_EMPLOYEE_BY_ID = 'EMPL_RESET_EMPLOYEE_BY_ID'

export const EMPL_ERROR = 'EMPL_ERROR'