export const SERVICE_LOADING = 'SERVICE_LOADING'

export const SERVICE_GET_SERVICE = 'SERVICE_GET_SERVICE'

export const SERVICE_ADD_SERVICE = 'SERVICE_ADD_SERVICE'

export const SERVICE_EDIT_SERVICE = 'SERVICE_EDIT_SERVICE'

export const SERVICE_GET_SERVICE_BY_ID = 'SERVICE_GET_SERVICE_BY_ID'

export const SERVICE_RESET_SERVICE_BY_ID = 'SERVICE_RESET_SERVICE_BY_ID'

export const SERVICE_ERROR = 'SERVICE_ERROR'